### ISSUE TITLE
Question of inverted LiDAR

### ISSUE THREAD

**Issue by siyiovo** [url-kaist/patchwork-plusplus#70]
Hi! I am appreciate your fantastic work! As title, my LiDAR ( Livox MID-360 ) is inverted(roll: 180 degree) and its height to the ground is 0.6m approximately, The LIO algorithm is Fast-LIO2. if input pointcloud of patchworkpp is as below, the segmentation is poor like below, too. I am wondering whether is valid to use the inverted pointcloud as input poincloud to segmentation? Should I transform it?

Here is the parameters:
```
/**:
    ros__parameters:
        sensor_height: -1.4 # Sensor height from ground, NOTE that +0.8m

        mode: "czm"
        verbose: true # To check effect of uprightness/elevation/flatness
        visualize: true # Ground Likelihood Estimation is visualized

        # Ground Plane Fitting parameters
        num_iter: 3 # Number of iterations for ground plane estimation using PCA.
        num_lpr: 20 # Maximum number of points to be selected as lowest points representative.
        num_min_pts: 10 # Minimum number of points to be estimated as ground plane in each patch.
        th_seeds: 0.3 # threshold for lowest point representatives using in initial seeds selection of ground points.
        th_dist: 0.125 # threshold for thickenss of ground.
        th_seeds_v: 0.25 # threshold for lowest point representatives using in initial seeds selection of vertical structural points.
        th_dist_v: 0.1 # threshold for thickenss of vertical structure.
        max_r: 15.0 # max_range of ground estimation area
        min_r: 0.3 # min_range of ground estimation area
        uprightness_thr: 0.707 # threshold of uprightness using in Ground Likelihood Estimation(GLE). Please refer paper for more information about GLE.

        adaptive_seed_selection_margin: -1.5 # The points below the adaptive_seed_selection_margin * sensor_height are filtered
        czm:
            num_zones: 4
            num_sectors_each_zone: [16, 32, 54, 32]
            mum_rings_each_zone: [2, 4, 4, 4]
            elevation_thresholds: [0.0, 0.0, 0.0, 0.0] # threshold of elevation for each ring using in GLE. Those values are updated adaptively.
            flatness_thresholds: [0.6, 0.5, 0.4, 0.3] # threshold of flatness for each ring using in GLE. Those values are updated adaptively.

        enable_RNR: true
        enable_RVPF: true
        enable_TGR: true

        RNR_ver_angle_thr: 15.0 # Noise points vertical angle threshold. Downward rays of LiDAR are more likely to generate severe noise points.
        RNR_intensity_thr: 0.6 # Noise points intensity threshold. The reflected points have relatively small intensity than others.

```

![Image](https://github.com/user-attachments/assets/a9f80734-58fc-45e8-860d-7c1dd466b691)
![Image](https://github.com/user-attachments/assets/38dfef89-2b61-400b-98c7-e9af127c9748)
